[package]
name = "kiwi-db"
version = "0.1.0"
edition = "2021"
authors = ["Amir Mousavi"]
description = "Kiwi-db is a key value database"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
